---
- name: Create AWS EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    instance_type: t3.xlarge
    ami_id: ami-0323c3dd2da7fb37d # CentOS 7 x86_64
    region: us-west-2
    key_name: my_key_pair
    security_group: my_security_group
    count: 6

  tasks:
    - name: Launch EC2 instances
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        count: "{{ count }}"
        instance_tags:
          Name: "CentOS 7 Instance {{ count.index + 1 }}"
      register: ec2_instances

    - name: Add instances to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: ec2
      with_items: "{{ ec2_instances.instances }}"

- name: Configure CentOS 7 instances
  hosts: ec2
  remote_user: centos
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: Install required packages
      yum:
        name:
          - epel-release
          - python3-pip
        state: present

    - name: Install AWS CLI
      pip:
        name: awscli

    - name: Set timezone to UTC
      timezone:
        name: UTC

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Disable firewall
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Update system packages
      yum:
        name: '*'
        state: latest
